version: "3"

services:
  #MySQL Service
  db:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_USER: root
      MYSQL_PASSWORD: dbpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  #Adminer Service  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  db:
    driver: local